### ISSUE TITLE
我的一些问题

### ISSUE THREAD

**Issue by canliture** [Lemonreds/javaee-blog#7]
刚学了些jsp/servlet，想在github上找源码看看，恰好找到你的这个项目。

大概两天时间，项目一直报错。
起初是我对c3p0与数据库之间的一些配置有问题，后来通过网上查找资料解决了问题。
起码首页能进去了。

后来的问题一直不能解决。一直是空指针异常。

at blog.daoImpl.ArticleDaoImpl.getColumAndCount(ArticleDaoImpl.java:107)
at blog.service.ArticleService.getSortAndCount(ArticleService.java:143)
at blog.servlet.LoginServlet.doGet(LoginServlet.java:34)
at blog.filter.VisitFilter.doFilter(VisitFilter.java:68)
at blog.filter.CodeFilter.doFilter(CodeFilter.java:41)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

请问能发邮箱，或者其它方式，跟你深入探讨一下吗？

**Comment by Lemonreds** [comment]
可以直接发一下异常的那一行代码吗？
